#!/usr/bin/env bash
# Check if the number of arguments passed is less than 4
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Check if the file exists
if [ ! -f "$file_path" ]; then
    echo "File '$file_path' not found."
    exit 1
fi

# Transfer the file using scp with strict host key checking disabled
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "${username}@${server_ip}:~/"

# Check if scp command executed successfully
if [ $? -eq 0 ]; then
    echo "File '$file_path' transferred successfully to ${username}@${server_ip}:~/"
else
    echo "Error transferring file '$file_path' to ${username}@${server_ip}:~/"
fi
