#!/usr/bin/env bash
# This script sets up Nginx and adds a custom HTTP header

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Create a configuration file for Nginx
cat <<EOL | sudo tee /etc/nginx/sites-available/default
server {
    listen 80;
    server_name BarbieCathy;

    location / {
        add_header X-Served-By "487685-web-01"; # Change to 487685-web-02 for the second server
        try_files \$uri \$uri/ =404;
    }
}
EOL

# Restart Nginx to apply changes
sudo systemctl restart nginx
