#!/usr/bin/env bash
# Script to configure Nginx with custom HTTP header X-Served-By

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure custom HTTP header in Nginx
sudo bash -c 'echo "
server {
    listen 80;
    server_name _;
    
    location / {
        add_header X-Served-By \$hostname;
    }
}" > /etc/nginx/sites-available/default'

# Restart Nginx to apply changes
sudo systemctl restart nginx
