#!/usr/bin/env bash
# Install Nginx if not already installed

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    maxconn 2000

defaults
    log     global
    mode    http
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 487685-web-01:80 check
    server web-02 487685-web-02:80 check
EOL

# Enable and start HAProxy
sudo systemctl enable haproxy
sudo systemctl start haproxy
