#!/usr/bin/env bash
# Update package list
apt-get update

# Install HAProxy
apt-get install -y haproxy

# Configure HAProxy to load balance between web servers
cat <<EOF > /etc/haproxy/haproxy.cfg
frontend web_front
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web-01 [web-01-private-IP]:80 check
    server web-02 [web-02-private-IP]:80 check
EOF

# Restart HAProxy to apply changes
service haproxy restart
