#!/usr/bin/env bash
# This script ensures Nginx is listening on port 80

apt-get update
apt-get install -y nginx
sed -i 's/^# server {/server {/' /etc/nginx/sites-available/default
systemctl restart nginx
