#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd in a specific format using the while loop and IFS.

while IFS=':' read -r username x uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $x, more info about the user here: $info"
done < /etc/passwd
