#!/usr/bin/env bash
# This script gives information about the school file: if it exists, if it's empty, and if it's a regular file.

if [ -e "school" ]; then
    echo "school file exists"
    if [ -s "school" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "school" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
