#!/usr/bin/env bash
# Script to configure Nginx to run as the nginx user and listen on port 8080
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart
