#!/usr/bin/env bash
# Short script to configure Nginx to run as nginx user
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart

